
class psppar:

    def __init__(self,element):
        self.element = element.upper()

    def create(self):

        f = open('psppar.' + self.element, 'w')

        if self.element == 'C':
            text = "HGH for Carbon (C) in PBE with NLCC,generated by Saha,2015\n"
#                        6    4  20150303 zatom, zion, date (yymmdd)"
            f.write(text)
            f.close()
#
#
#F = psppar('C')
#print(F.element)
#print(type(F.element))
#print(F.element == 'C')
#
#F.create()
